// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9mwfR3qghaRT2d3xUuizG1Z_CvpZOq_c',
    appId: '1:112732122079:web:3b2a4f2dc280838790f26a',
    messagingSenderId: '112732122079',
    projectId: 'hpp-project-f1d88',
    authDomain: 'hpp-project-f1d88.firebaseapp.com',
    storageBucket: 'hpp-project-f1d88.appspot.com',
    measurementId: 'G-54WZ3H242Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcMeqEvjQOG6-qhnJKPjA8gglDezExmjk',
    appId: '1:112732122079:android:267127df828c8c4890f26a',
    messagingSenderId: '112732122079',
    projectId: 'hpp-project-f1d88',
    storageBucket: 'hpp-project-f1d88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwDADYfI9a6sMwp6MVmELLmEeKhrPRUxo',
    appId: '1:112732122079:ios:c46961da54e1c33690f26a',
    messagingSenderId: '112732122079',
    projectId: 'hpp-project-f1d88',
    storageBucket: 'hpp-project-f1d88.appspot.com',
    iosBundleId: 'com.example.hppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwDADYfI9a6sMwp6MVmELLmEeKhrPRUxo',
    appId: '1:112732122079:ios:c46961da54e1c33690f26a',
    messagingSenderId: '112732122079',
    projectId: 'hpp-project-f1d88',
    storageBucket: 'hpp-project-f1d88.appspot.com',
    iosBundleId: 'com.example.hppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9mwfR3qghaRT2d3xUuizG1Z_CvpZOq_c',
    appId: '1:112732122079:web:fd5a56a1069e5faa90f26a',
    messagingSenderId: '112732122079',
    projectId: 'hpp-project-f1d88',
    authDomain: 'hpp-project-f1d88.firebaseapp.com',
    storageBucket: 'hpp-project-f1d88.appspot.com',
    measurementId: 'G-4GDGH5ZY33',
  );
}
